chore(workflows): add types and website area field automatically

diff --git a/.github/workflows/issue-triage.yml b/.github/workflows/issue-triage.yml
--- a/.github/workflows/issue-triage.yml
+++ b/.github/workflows/issue-triage.yml
@@ -4,9 +4,38 @@ on:
     types: [opened]
   issue_comment:
     types: [created]
+env:
+  ISSUE_NUMBER: ${{ github.event.issue.number }}
 jobs:
   issue-triage:
     uses: carbon-design-system/carbon/.github/workflows/issue-triage.yml@main
     secrets:
       APP_ID: ${{ secrets.APP_ID }}
       APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
+  set-area-per-repo:
+    needs: setup-variables
+    runs-on: ubuntu-latest
+    if: ${{ github.event_name == 'issues' && github.event.action == 'opened' }}
+    steps:
+      - uses: actions/create-github-app-token@v1
+        id: app-token
+        with:
+          app-id: ${{ secrets.APP_ID }}
+          private-key: ${{ secrets.PRIVATE_KEY }}
+      - name: Get issue ID
+        id: get_issue_id
+        run: |
+            ISSUE_ID=$(gh project item-list $PROJECT_ID --owner=$OWNER --limit=$ITEM_FETCH_LIMIT --format=json --jq ".items[] | select(.content.number == $ISSUE_NUMBER and .content.repository == $REPOSITORY) | .id" -r)
+            if [ -z "$ISSUE_ID" ]; then
+              echo "Issue ID not found for issue number $ISSUE_NUMBER"
+              exit 1
+            fi
+            echo "Issue ID is $ISSUE_ID"
+            echo "issue_id=$ISSUE_ID" >> "$GITHUB_OUTPUT"
+      - name: Update issue with website area field
+        run:
+          gh project item-edit --project-id 39 --id $ISSUE_ID
+          --field-id PVTSSF_lADOAYA3Ss1Nv84BfRL4 --single-select-option-id 113a0859
+        env:
+          GH_TOKEN: ${{ steps.app-token.outputs.token }}
+          $ISSUE_ID: ${{ steps.get_issue_id.outputs.issue_id }}
